/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shugalev.myrest;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasUsersCredentials() {
        UsersCredentials classUnderTest = new UsersCredentials();
        assertNotNull(classUnderTest.getUsersCredentials(), "app should have cred");
    }

    private static class App {

        public App() {
        }
    }
}
